### ISSUE TITLE
Can't run peda-arm

### ISSUE THREAD

**Issue by owlinux1000** [alset0326/peda-arm#2]
Environment:
* GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
* Ubuntu16.04
* Python 2.7.12(default)

```
[*] Loading components.
[*] Loading peda main section.
[*] registering commands.
~~skip~~
Modified by alset v1.0

Traceback (most recent call last):
  File "/home/vagrant/ctf/tools/peda-arm/peda-arm.py", line 54, in <module>
    from asm import *
  File "/home/vagrant/ctf/tools/peda-arm/lib/asm.py", line 17, in <module>
    if config.prefix == '':
AttributeError: module 'config' has no attribute 'prefix' 
```

**Comment by alset0326** [comment]
You were using the [peda repo](https://github.com/alset0326/peda), not the [peda-arm repo](https://github.com/alset0326/peda-arm). Please download and try again. Have fun :)

**Comment by owlinux1000** [comment]
Thanks!

I made a mistake.
Now, I only use peda-arm.  But an error occured.

```
[*] Loading components.
Traceback (most recent call last):
  File "/home/vagrant/ctf/tools/peda-arm/peda-arm.py", line 88, in <module>
    SYSTEM_CALLS = pickle.loads(zlib.decompress(f.read()))
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
(gdb)
```

**Comment by owlinux1000** [comment]
I solved this error :)

1. open mode changed. r -> rb (in peda-arm.py)
2. remake ```system_calls``` file in Python3(and delete '\xe2\x80\x90' in system_calls file)

**Comment by alset0326** [comment]
Awesome!
It will be fixed!
